"""Phases 19, 21 and 22: what an upgrade has to survive, and whether the release was signed off
and recorded."""

from __future__ import annotations

import json
import re

from .constants import AFTER_TAG, BUNDLE_FORMAT_PATHS, FAIL, WARN
from .core import Ctx, Outcome, check, fail, ok, skip, verdict, warn
from .evaluate import alembic_heads, manual_ids, parse_record


@check("A19.01", 19, "The migration chain has exactly one head")
def single_head(ctx: Ctx) -> Outcome:
    revisions = {}
    for f in sorted((ctx.root / "backend/alembic/versions").glob("*.py")):
        text = f.read_text(encoding="utf-8")
        # Both quote styles and any annotation: autogenerated revisions use single quotes.
        rev = re.search(r"""^revision(?:\s*:[^=]+)?\s*=\s*['"]([^'"]+)['"]""", text, re.M)
        down = re.search(
            r"""^down_revision(?:\s*:[^=]+)?\s*=\s*(None|['"][^'"]+['"])""", text, re.M
        )
        if rev:
            revisions[rev[1]] = None if not down or down[1] == "None" else down[1].strip("'\"")
    heads = alembic_heads(revisions)
    return verdict(
        [] if len(heads) == 1 else [f"heads: {heads}"],
        f"{len(revisions)} revisions, head {heads[0] if heads else None}",
    )


@check(
    "A19.02",
    19,
    "Schema and bundle-format changes since the previous release are declared",
    stages=("pre-tag", *AFTER_TAG),
    stop=False,
)
def upgrade_surface(ctx: Ctx) -> Outcome:
    prev = ctx.previous_tag()
    if prev is None:
        return skip("no previous release")
    span = f"{prev}..{ctx.release_commit()}"
    evidence = {
        "migrations": ctx.git(
            "diff", "--name-only", "--diff-filter=A", span, "--", "backend/alembic/versions/"
        ).split(),
        "models": ctx.git("diff", "--name-only", span, "--", "backend/app/models").split(),
        "bundle_format": ctx.git("diff", "--name-only", span, "--", *BUNDLE_FORMAT_PATHS).split(),
    }
    if any(evidence.values()):
        return warn(
            "the upgrade checks in Phase 19 are required: " + json.dumps(evidence), **evidence
        )
    return ok(f"no schema, model or bundle-format change since {prev}", **evidence)


@check(
    "A21.01", 21, "The record accounts for every manual check and is signed off", stages=AFTER_TAG
)
def record_complete(ctx: Ctx) -> Outcome:
    if not ctx.record_path.exists():
        return fail("no release record")
    wanted = manual_ids(ctx.read("RELEASE.md"))
    statuses, approved = parse_record(ctx.record_path.read_text(encoding="utf-8"))
    problems = []
    if missing := [m for m in wanted if m not in statuses]:
        problems.append(f"{len(missing)} manual checks have no row: {', '.join(missing)}")
    if failed := [m for m, s in statuses.items() if s == "FAIL"]:
        problems.append(f"FAIL: {', '.join(failed)}")
    if pending := [m for m, s in statuses.items() if s == "PENDING"]:
        problems.append(f"PENDING: {', '.join(pending)}")
    if not approved:
        problems.append("not signed off")
    counts = {s: list(statuses.values()).count(s) for s in sorted(set(statuses.values()))}
    if problems:
        # Before the flip the record is still being filled in; after it, it is the release.
        return Outcome(
            FAIL if ctx.stage == "post-release" else WARN, "; ".join(problems), {"counts": counts}
        )
    return ok(f"{len(wanted)} manual checks recorded, signed off", counts=counts)


@check("A22.01", 22, "The release record is on main", stages=("post-release",), network=True)
def record_on_main(ctx: Ctx) -> Outcome:
    rel = str(ctx.record_path.relative_to(ctx.root))
    return (
        ok(rel)
        if ctx.git_ok("cat-file", "-e", f"origin/main:{rel}")
        else fail(f"{rel} is not on origin/main")
    )
