"""
Scoped follow-up questions (docs/07 §2, Phase 5; req 8).

A follow-up can be pinned to what it may read: this report, the uploaded corpus, the
open web, or everything. The claim the UI makes about each scope is the thing under
test — a selector that says "no web search" and then searches the web is worse than no
selector at all.

**On the zero-egress claim.** The plan's wording is "corpus scope makes zero network
calls". That is not true of a chat turn and this suite does not pretend it is: the
answer is generated by a model, which is remote unless the user routed chat to a local
one. What *is* true, and what is asserted here, is that corpus scope performs no
**retrieval** egress — no web retriever runs, and the query embedding is refused outright
rather than quietly sent off-machine when the configured embedder is remote.

That distinction is the point of the phase, not a hedge around it: `test_corpus_egress.py`
was green for years while the query embedding egressed, precisely because the assertion
was broader than what the test could actually see. So the guard here is exercised with a
**real** remote embedder and a real refusal, never with the egressing call stubbed out.
"""

from __future__ import annotations

import pytest

from app.services import chat_scope
from research_engine.embeddings import EmbeddingsUnavailable


class _Embedder:
    """A real Embeddings-shaped object. `is_local` is the field the airgap guard reads,
    and it is what varies between the two cases below — not a patched-out method."""

    def __init__(self, *, is_local: bool) -> None:
        self.is_local = is_local
        self.model_id = "ollama:nomic-embed-text" if is_local else "openai:text-embedding-3-small"
        self.calls = 0

    async def embed(self, texts: list[str]) -> list[list[float]]:
        self.calls += 1
        return [[0.1, 0.2, 0.3] for _ in texts]


class _ExplodingRetriever:
    """Stands in for the web chain. Any call is the failure being tested for."""

    def __init__(self) -> None:
        self.calls: list[str] = []

    async def __call__(self, query: str, max_results: int = 5):
        self.calls.append(query)
        raise AssertionError(f"a web search ran for scope that forbids it: {query!r}")


# ── The scope vocabulary ───────────────────────────────────────────────────────────


def test_every_scope_states_what_it_reads_and_what_it_does_not():
    """The selector's promise is machine-readable, so the copy cannot drift from the
    behaviour. Each entry names both halves — a scope that only said what it *includes*
    would let "Web" quietly also read the corpus."""
    for scope in chat_scope.SCOPES:
        described = chat_scope.describe(scope)
        assert described.label
        assert described.reads, f"{scope} does not say what it reads"
        assert described.excludes, f"{scope} does not say what it will not touch"


def test_report_is_the_default_so_an_omitted_scope_changes_nothing():
    """Today's behaviour on both chat surfaces is grounding in finished research. An
    un-updated client that sends no scope must keep exactly that."""
    from app.schemas.research import ChatRequest

    assert ChatRequest(message="hi").scope == "report"


# ── Corpus scope: no retrieval egress ──────────────────────────────────────────────


@pytest.mark.asyncio
async def test_corpus_scope_refuses_a_remote_embedder_rather_than_embedding_off_machine():
    """The one call corpus retrieval makes is the query embedding, and it is the call
    that would leave the machine. The guard must fire on the real embedder's own
    `is_local`, before `embed` is reached."""
    embedder = _Embedder(is_local=False)

    with pytest.raises(EmbeddingsUnavailable) as exc:
        await chat_scope.corpus_excerpts(
            store_factory=lambda: _FakeStore(embedder),
            query="what did the uploaded papers say about recall?",
        )

    assert "remote" in str(exc.value).lower()
    assert embedder.calls == 0, "the query must not be embedded before the guard runs"


@pytest.mark.asyncio
async def test_corpus_scope_never_reaches_the_web_chain(monkeypatch):
    """Asserted against the real `retrievers.search` module attribute, not a stubbed
    `chat_scope` internal — replacing the thing under test is the decorative-test trap
    (AGENTS.md)."""
    exploding = _ExplodingRetriever()
    monkeypatch.setattr("research_engine.retrievers.search", exploding)

    grounding = await chat_scope.gather(
        "corpus",
        query="recall of dense retrievers",
        report=None,
        report_sources=[],
        memory_excerpts=None,
        store_factory=lambda: _FakeStore(_Embedder(is_local=True)),
    )

    assert exploding.calls == []
    assert grounding.scope == "corpus"
    assert "uploaded" in grounding.text.lower() or grounding.text


@pytest.mark.asyncio
async def test_corpus_scope_says_so_when_the_project_has_no_corpus():
    """An empty corpus is an answerable state, not an error — but the answer has to say
    the shelf was empty rather than let the model fill the silence."""
    grounding = await chat_scope.gather(
        "corpus",
        query="anything",
        report=None,
        report_sources=[],
        memory_excerpts=None,
        store_factory=lambda: None,
    )

    assert grounding.notes, "a missing corpus must be reported, not silently empty"
    assert "corpus" in " ".join(grounding.notes).lower()


# ── Report scope: unchanged behaviour ──────────────────────────────────────────────


@pytest.mark.asyncio
async def test_report_scope_reads_the_report_and_runs_no_retrieval(monkeypatch):
    exploding = _ExplodingRetriever()
    monkeypatch.setattr("research_engine.retrievers.search", exploding)

    grounding = await chat_scope.gather(
        "report",
        query="what were the limitations?",
        report="# Findings\n\nDense retrieval improved recall [1].",
        report_sources=[{"index": 1, "url": "https://example.com", "title": "A paper"}],
        memory_excerpts=None,
        store_factory=lambda: None,
    )

    assert exploding.calls == []
    assert "Dense retrieval improved recall" in grounding.text
    assert grounding.sources == []


# ── Web scope: new sources, and they come back ─────────────────────────────────────


@pytest.mark.asyncio
async def test_web_scope_returns_the_sources_it_found(monkeypatch):
    """A web-scoped answer cites pages the report never had, so those sources have to
    reach the client — otherwise its `[n]` markers resolve to nothing, which is the one
    thing this product refuses to ship."""

    async def fake_search(query: str, max_results: int = 5):
        return [
            {"url": "https://arxiv.org/abs/1", "title": "Recent work", "content": "A finding."},
        ]

    monkeypatch.setattr("research_engine.retrievers.search", fake_search)

    grounding = await chat_scope.gather(
        "web",
        query="2026 results",
        report=None,
        report_sources=[],
        memory_excerpts=None,
        store_factory=lambda: None,
    )

    assert [s["url"] for s in grounding.sources] == ["https://arxiv.org/abs/1"]
    assert "Recent work" in grounding.text
    # Numbered from 1 so the model's [n] markers resolve against this list.
    assert grounding.sources[0]["index"] == 1


@pytest.mark.asyncio
async def test_a_failed_web_search_is_reported_not_swallowed(monkeypatch):
    """AGENTS.md, "never fake, never swallow": an unavailable retriever must reach the
    answer as a stated gap, not as an empty grounding block the model papers over."""

    async def boom(query: str, max_results: int = 5):
        raise RuntimeError("every retriever failed: tavily 429, brave 401")

    monkeypatch.setattr("research_engine.retrievers.search", boom)

    grounding = await chat_scope.gather(
        "web",
        query="anything",
        report=None,
        report_sources=[],
        memory_excerpts=None,
        store_factory=lambda: None,
    )

    assert grounding.sources == []
    assert any("429" in n or "retriever" in n.lower() for n in grounding.notes)


# ── Everything scope ───────────────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_everything_scope_combines_every_available_ground(monkeypatch):
    async def fake_search(query: str, max_results: int = 5):
        return [{"url": "https://arxiv.org/abs/2", "title": "Web hit", "content": "Fresh."}]

    monkeypatch.setattr("research_engine.retrievers.search", fake_search)

    grounding = await chat_scope.gather(
        "everything",
        query="q",
        report="# Report\n\nA prior finding [1].",
        report_sources=[{"index": 1, "url": "https://example.com", "title": "Prior"}],
        memory_excerpts=None,
        store_factory=lambda: _FakeStore(_Embedder(is_local=True)),
    )

    assert "A prior finding" in grounding.text
    assert "Web hit" in grounding.text
    assert "corpus excerpt" in grounding.text.lower()
    assert grounding.sources


# ── A store that behaves like CorpusStore without needing a file ───────────────────


class _FakeStore:
    """Exercises the *real* guard: `search` runs the same `is_local` check `CorpusStore`
    does, so a test that passes here would pass against the real store for the same
    reason. Only the SQLite file is absent."""

    def __init__(self, embedder: _Embedder) -> None:
        self._embedder = embedder

    async def search(self, query: str, max_results: int) -> list[dict]:
        if not getattr(self._embedder, "is_local", False):
            raise EmbeddingsUnavailable(
                f"Corpus scope reads only your uploaded documents, but the configured "
                f"embeddings provider '{self._embedder.model_id}' is remote — every "
                f"corpus search would send the question off this machine."
            )
        await self._embedder.embed([query])
        return [
            {
                "url": "corpus://paper.pdf#p3",
                "title": "paper.pdf (p. 3)",
                "content": "Corpus excerpt about recall.",
            }
        ]
