"""user_api_key_base_url

Revision ID: e9f72cd4cd56
Revises: 0009_corpus_mode
Create Date: 2026-08-13 13:11:16.310643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9f72cd4cd56'
down_revision: Union[str, None] = '0009_corpus_mode'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_base_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key_base_url')
    # ### end Alembic commands ###
