"""research domain tables

Revision ID: eafdf189af24
Revises: 0015_citation_resolution_rate
Create Date: 2026-08-17 19:15:11.687507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# `project_memory_items.embedding` is a pgvector column; autogenerate renders the type
# but does not emit its import.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eafdf189af24'
down_revision: Union[str, None] = '0015_citation_resolution_rate'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_actor', 'audit_events', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_subject', 'audit_events', ['subject_type', 'subject_id', 'id'], unique=False)
    op.create_table('project_memory_items',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('project_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('provenance_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_project_memory_items_ck_memory_chunk')),
    sa.CheckConstraint('length(provenance_digest) = 64', name=op.f('ck_project_memory_items_ck_memory_digest')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_memory_items_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_memory_items')),
    sa.UniqueConstraint('project_id', 'embedding_model', 'provenance_digest', 'chunk_index', name='uq_memory_chunk')
    )
    op.create_index(op.f('ix_project_memory_items_project_id'), 'project_memory_items', ['project_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('project_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('depth', sa.String(length=16), nullable=False),
    sa.Column('corpus_mode', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('skip_plan_gate', sa.Boolean(), nullable=False),
    sa.Column('topic_seeds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('outline_template', sa.String(length=64), nullable=True),
    sa.Column('model_routing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('tokens_input', sa.BigInteger(), nullable=False),
    sa.Column('tokens_output', sa.BigInteger(), nullable=False),
    sa.Column('elapsed_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('citation_resolution_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'CANCELLED') = (cancelled_at IS NOT NULL)", name=op.f('ck_research_runs_ck_run_cancelled')),
    sa.CheckConstraint("depth IN ('fast', 'balanced', 'comprehensive')", name=op.f('ck_research_runs_ck_run_depth')),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'AWAITING_PLAN', 'AWAITING_REVIEW', 'COMPLETED', 'FAILED', 'CANCELLED')", name=op.f('ck_research_runs_ck_run_status')),
    sa.CheckConstraint('citation_resolution_rate IS NULL OR (citation_resolution_rate >= 0 AND citation_resolution_rate <= 1)', name=op.f('ck_research_runs_ck_run_resolution')),
    sa.CheckConstraint('cost_usd >= 0 AND tokens_input >= 0 AND tokens_output >= 0', name=op.f('ck_research_runs_ck_run_metrics')),
    sa.ForeignKeyConstraint(['cancel_requested_by'], ['users.id'], name=op.f('fk_research_runs_cancel_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_research_runs_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index(op.f('ix_research_runs_project_id'), 'research_runs', ['project_id'], unique=False)
    op.create_index('ix_run_owner_status', 'research_runs', ['owner_id', 'status'], unique=False)
    op.create_index('ix_run_project_recent', 'research_runs', ['project_id', 'archived_at', 'created_at'], unique=False)
    op.create_table('research_plans',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tasks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outline_sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('MODEL_PROPOSED', 'HUMAN_EDITED', 'TEMPLATE', 'UNKNOWN')", name=op.f('ck_research_plans_ck_plan_origin')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_research_plans_ck_plan_version')),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_plans_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plans')),
    sa.UniqueConstraint('run_id', 'version', name='uq_plan_version')
    )
    op.create_index('uq_plan_approved', 'research_plans', ['run_id'], unique=True, postgresql_where=sa.text('approved_at IS NOT NULL'), sqlite_where=sa.text('approved_at IS NOT NULL'))
    op.create_table('revisions',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_watermark', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('evidence_watermark >= 0', name=op.f('ck_revisions_ck_revision_wm')),
    sa.CheckConstraint('length(report_hash) = 64', name=op.f('ck_revisions_ck_revision_hash')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_revisions_ck_revision_version')),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_revisions_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisions')),
    sa.UniqueConstraint('id', 'run_id', name='uq_revision_run'),
    sa.UniqueConstraint('run_id', 'version', name='uq_revision_version')
    )
    op.create_index('ix_revision_run_version', 'revisions', ['run_id', 'version'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('retrieval_status', sa.String(length=20), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('corpus_document_id', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'CORPUS') = (corpus_document_id IS NOT NULL)", name=op.f('ck_sources_ck_source_corpus')),
    sa.CheckConstraint("kind IN ('WEB', 'CORPUS')", name=op.f('ck_sources_ck_source_kind')),
    sa.CheckConstraint("retrieval_status IN ('FETCHED', 'SEARCH_RESULT_ONLY', 'FAILED', 'UNKNOWN')", name=op.f('ck_sources_ck_source_ret')),
    sa.CheckConstraint('citation_index >= 1', name=op.f('ck_sources_ck_source_cidx')),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_sources_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('id', 'run_id', name='uq_source_run'),
    sa.UniqueConstraint('run_id', 'citation_index', name='uq_source_index'),
    sa.UniqueConstraint('run_id', 'normalized_url', name='uq_source_url')
    )
    op.create_table('claims',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('revision_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=24), nullable=False),
    sa.Column('verification_state', sa.String(length=24), nullable=False),
    sa.Column('verification_method', sa.String(length=20), nullable=False),
    sa.Column('lineage_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(verification_state = 'UNCHECKED') = (verification_method = 'NOT_RUN')", name=op.f('ck_claims_ck_claim_unchecked')),
    sa.CheckConstraint("extraction_method IN ('DERIVED_FROM_REPORT', 'MODEL_STRUCTURED', 'HUMAN_EDITED')", name=op.f('ck_claims_ck_claim_extract')),
    sa.CheckConstraint("verification_method IN ('NUMERIC_GROUNDING', 'MODEL_JUDGE', 'NOT_RUN')", name=op.f('ck_claims_ck_claim_method')),
    sa.CheckConstraint("verification_state IN ('SUPPORTED', 'UNSUPPORTED', 'INSUFFICIENT_EVIDENCE', 'UNCHECKED')", name=op.f('ck_claims_ck_claim_state')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_claims_ck_claim_position')),
    sa.ForeignKeyConstraint(['revision_id', 'run_id'], ['revisions.id', 'revisions.run_id'], name='fk_claim_revision', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('id', 'run_id', name='uq_claim_run'),
    sa.UniqueConstraint('revision_id', 'position', name='uq_claim_position')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('source_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('key_fact', sa.Text(), nullable=True),
    sa.Column('provenance_state', sa.String(length=12), nullable=False),
    sa.Column('attested_against', sa.String(length=20), nullable=True),
    sa.Column('attestation_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(attested_against IS NOT NULL) = (provenance_state = 'ATTESTED')", name=op.f('ck_evidence_ck_ev_grade')),
    sa.CheckConstraint("(provenance_state = 'UNCHECKED') = (attestation_run_at IS NULL)", name=op.f('ck_evidence_ck_ev_unchecked')),
    sa.CheckConstraint("attested_against IS NULL OR attested_against IN ('FETCHED_BODY', 'SEARCH_SNIPPET', 'CORPUS_DOCUMENT')", name=op.f('ck_evidence_ck_ev_grade_vocab')),
    sa.CheckConstraint("provenance_state IN ('ATTESTED', 'UNATTESTED', 'UNCHECKED')", name=op.f('ck_evidence_ck_ev_state')),
    sa.CheckConstraint('sequence >= 1', name=op.f('ck_evidence_ck_ev_seq')),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_evidence_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id', 'run_id'], ['sources.id', 'sources.run_id'], name='fk_evidence_source', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('id', 'run_id', name='uq_evidence_run'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_evidence_seq')
    )
    op.create_index('ix_evidence_source', 'evidence', ['source_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('revision_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('reviewer_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('plan_version_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('gate', sa.String(length=8), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(gate = 'PLAN') = (plan_version_id IS NOT NULL)", name=op.f('ck_reviews_ck_review_plan')),
    sa.CheckConstraint("decision IN ('APPROVED', 'REWORK_REQUESTED', 'REJECTED')", name=op.f('ck_reviews_ck_review_decision')),
    sa.CheckConstraint("gate IN ('PLAN', 'REPORT')", name=op.f('ck_reviews_ck_review_gate')),
    sa.CheckConstraint('length(reviewed_hash) = 64', name=op.f('ck_reviews_ck_review_hash')),
    sa.ForeignKeyConstraint(['plan_version_id'], ['research_plans.id'], name=op.f('fk_reviews_plan_version_id_research_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], name=op.f('fk_reviews_revision_id_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('id', 'decision', name='uq_review_decision')
    )
    op.create_index('ix_review_revision', 'reviews', ['revision_id', 'created_at'], unique=False)
    op.create_index('uq_review_approval', 'reviews', ['revision_id'], unique=True, postgresql_where=sa.text("decision = 'APPROVED' AND gate = 'REPORT'"), sqlite_where=sa.text("decision = 'APPROVED' AND gate = 'REPORT'"))
    op.create_table('claim_annotations',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('claim_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('author_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('FLAG_UNSUPPORTED', 'REQUEST_EVIDENCE', 'COMMENT')", name=op.f('ck_claim_annotations_ck_annotation_kind')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_claim_annotations_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_annotations_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_annotations'))
    )
    op.create_index(op.f('ix_claim_annotations_claim_id'), 'claim_annotations', ['claim_id'], unique=False)
    op.create_table('claim_evidence_links',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('claim_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('evidence_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('stance', sa.String(length=12), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('CITATION_MARKER', 'MODEL_ASSERTED', 'HUMAN_ASSERTED')", name=op.f('ck_claim_evidence_links_ck_link_origin')),
    sa.CheckConstraint("stance IN ('SUPPORTS', 'CONTRADICTS', 'CONTEXT')", name=op.f('ck_claim_evidence_links_ck_link_stance')),
    sa.ForeignKeyConstraint(['claim_id', 'run_id'], ['claims.id', 'claims.run_id'], name='fk_link_claim', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id', 'run_id'], ['evidence.id', 'evidence.run_id'], name='fk_link_evidence', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence_links')),
    sa.UniqueConstraint('claim_id', 'evidence_id', name='uq_link')
    )
    op.create_index('ix_link_claim', 'claim_evidence_links', ['claim_id'], unique=False)
    op.create_index('ix_link_evidence', 'claim_evidence_links', ['evidence_id'], unique=False)
    op.create_table('contradictions',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('evidence_a_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('evidence_b_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('summary_a', sa.Text(), nullable=True),
    sa.Column('summary_b', sa.Text(), nullable=True),
    sa.Column('dimension', sa.String(length=20), nullable=True),
    sa.Column('detection_state', sa.String(length=24), nullable=False),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(detection_state = 'DETECTED') = (evidence_a_id IS NOT NULL AND evidence_b_id IS NOT NULL)", name=op.f('ck_contradictions_ck_contra_pair')),
    sa.CheckConstraint("detection_state IN ('DETECTED', 'NOT_RUN', 'DETECTOR_UNAVAILABLE')", name=op.f('ck_contradictions_ck_contra_state')),
    sa.CheckConstraint("dimension IS NULL OR dimension IN ('TIMEFRAME', 'METHODOLOGY', 'POPULATION', 'WORKLOAD', 'SOURCE_QUALITY', 'UNCLASSIFIED')", name=op.f('ck_contradictions_ck_contra_dim')),
    sa.CheckConstraint("review_state IN ('UNREVIEWED', 'ACKNOWLEDGED', 'DISMISSED')", name=op.f('ck_contradictions_ck_contra_review')),
    sa.CheckConstraint('evidence_a_id IS NULL OR evidence_a_id <> evidence_b_id', name=op.f('ck_contradictions_ck_contra_distinct')),
    sa.ForeignKeyConstraint(['evidence_a_id', 'run_id'], ['evidence.id', 'evidence.run_id'], name='fk_contra_a', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_b_id', 'run_id'], ['evidence.id', 'evidence.run_id'], name='fk_contra_b', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_contradictions_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contradictions'))
    )
    op.create_index(op.f('ix_contradictions_run_id'), 'contradictions', ['run_id'], unique=False)
    op.create_table('research_artifacts',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('project_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('revision_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('review_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('review_decision', sa.String(length=20), nullable=False),
    sa.Column('format_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_decision = 'APPROVED'", name=op.f('ck_research_artifacts_ck_artifact_approved')),
    sa.CheckConstraint('format_version >= 1', name=op.f('ck_research_artifacts_ck_artifact_format')),
    sa.CheckConstraint('length(artifact_hash) = 64', name=op.f('ck_research_artifacts_ck_artifact_hashlen')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_research_artifacts_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_research_artifacts_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id', 'review_decision'], ['reviews.id', 'reviews.decision'], name='fk_artifact_review', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], name=op.f('fk_research_artifacts_revision_id_revisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], name=op.f('fk_research_artifacts_run_id_research_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_artifacts')),
    sa.UniqueConstraint('artifact_hash', name='uq_artifact_hash')
    )
    op.create_index('ix_artifact_owner', 'research_artifacts', ['owner_id', 'created_at'], unique=False)
    op.create_index('uq_artifact_run', 'research_artifacts', ['run_id'], unique=True, postgresql_where=sa.text('run_id IS NOT NULL'), sqlite_where=sa.text('run_id IS NOT NULL'))
    op.create_table('project_memory_provenance',
    sa.Column('memory_item_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('artifact_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['research_artifacts.id'], name=op.f('fk_project_memory_provenance_artifact_id_research_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_item_id'], ['project_memory_items.id'], name=op.f('fk_project_memory_provenance_memory_item_id_project_memory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_item_id', 'artifact_id', name=op.f('pk_project_memory_provenance'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_memory_provenance')
    op.drop_index('uq_artifact_run', table_name='research_artifacts', postgresql_where=sa.text('run_id IS NOT NULL'), sqlite_where=sa.text('run_id IS NOT NULL'))
    op.drop_index('ix_artifact_owner', table_name='research_artifacts')
    op.drop_table('research_artifacts')
    op.drop_index(op.f('ix_contradictions_run_id'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index('ix_link_evidence', table_name='claim_evidence_links')
    op.drop_index('ix_link_claim', table_name='claim_evidence_links')
    op.drop_table('claim_evidence_links')
    op.drop_index(op.f('ix_claim_annotations_claim_id'), table_name='claim_annotations')
    op.drop_table('claim_annotations')
    op.drop_index('uq_review_approval', table_name='reviews', postgresql_where=sa.text("decision = 'APPROVED' AND gate = 'REPORT'"), sqlite_where=sa.text("decision = 'APPROVED' AND gate = 'REPORT'"))
    op.drop_index('ix_review_revision', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_evidence_source', table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('claims')
    op.drop_table('sources')
    op.drop_index('ix_revision_run_version', table_name='revisions')
    op.drop_table('revisions')
    op.drop_index('uq_plan_approved', table_name='research_plans', postgresql_where=sa.text('approved_at IS NOT NULL'), sqlite_where=sa.text('approved_at IS NOT NULL'))
    op.drop_table('research_plans')
    op.drop_index('ix_run_project_recent', table_name='research_runs')
    op.drop_index('ix_run_owner_status', table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_project_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_project_memory_items_project_id'), table_name='project_memory_items')
    op.drop_table('project_memory_items')
    op.drop_index('ix_audit_subject', table_name='audit_events')
    op.drop_index('ix_audit_actor', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
