#!/usr/bin/env python3
"""
Stamp the build with the revision that produced it.

Writes `backend/research_engine/_build.py`, which `research_engine.build_info` reads and
`GET /version` serves. Git-ignored on purpose: a source checkout has no stamp, and
`build_info()` answers `unknown` rather than guessing from the working tree — a guess is
wrong exactly when it matters, which is a bundle built from a dirty tree or copied
between machines.

Run before packaging, on both hosts:

    python scripts/stamp_build.py

`--check` verifies an existing stamp matches the current checkout, which is what CI asserts
against a frozen sidecar.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STAMP = ROOT / "backend" / "research_engine" / "_build.py"


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def contract_version() -> str:
    """A hash of the canonical API surface: every operation and its response shape.

    Not the whole OpenAPI document — descriptions and summaries change with prose, and a
    contract hash that moves when someone improves a docstring is a hash nobody will trust.
    """
    # Placeholder configuration, set only to build the app object for introspection.
    # `app.config` requires a DSN and a signing key at import, and this script also runs on
    # the desktop build, which has neither. Nothing here connects to anything: the OpenAPI
    # document is assembled from route declarations. `setdefault`, so a configured
    # environment keeps its own values.
    import os  # noqa: PLC0415

    os.environ.setdefault("DATABASE_URL", "postgresql+asyncpg://stamp:stamp@localhost/stamp")
    os.environ.setdefault("JWT_SECRET_KEY", "stamp-" + "0" * 32)

    sys.path.insert(0, str(ROOT / "backend"))
    from app.main import app  # noqa: PLC0415

    surface = {}
    for path, item in app.openapi()["paths"].items():
        for method, operation in item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            responses = {
                code: (resp.get("content") or {}).get("application/json", {}).get("schema")
                for code, resp in (operation.get("responses") or {}).items()
            }
            surface[f"{method.upper()} {path}"] = responses
    canonical = json.dumps(surface, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()[:16]


def stamp() -> dict:
    return {
        "VERSION": (ROOT / "VERSION").read_text(encoding="utf-8").strip(),
        "GIT_SHA": _git("rev-parse", "HEAD"),
        "DIRTY": bool(_git("status", "--porcelain")),
        "CONTRACT_VERSION": contract_version(),
        "BUILT_AT": datetime.now(UTC).isoformat(timespec="seconds"),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify an existing stamp")
    args = parser.parse_args()

    current = stamp()
    if args.check:
        if not STAMP.exists():
            print("no build stamp — run scripts/stamp_build.py before packaging", file=sys.stderr)
            return 1
        # Parsed, not string-matched. The first version of this compared against its own
        # output format and disagreed with a stamp it had just written, because `repr`
        # renders single quotes — a check that fails on formatting tells you nothing about
        # the thing it is supposed to be checking.
        import ast  # noqa: PLC0415

        recorded = {}
        for node in ast.parse(STAMP.read_text(encoding="utf-8")).body:
            if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
                recorded[node.targets[0].id] = ast.literal_eval(node.value)

        for key in ("VERSION", "GIT_SHA"):
            if recorded.get(key) != current[key]:
                print(
                    f"stamp says {key}={recorded.get(key)!r}, checkout says {current[key]!r}",
                    file=sys.stderr,
                )
                return 1
        print(f"build stamp matches this checkout ({current['GIT_SHA'][:9]})")
        return 0

    lines = [
        '"""Generated by scripts/stamp_build.py. Not checked in; see build_info.py."""',
        "",
    ]
    for key, value in current.items():
        lines.append(f"{key} = {value!r}")
    STAMP.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"stamped {current['GIT_SHA'][:9]}{' (dirty)' if current['DIRTY'] else ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
